# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔹 Nouvelle étape pour remplacer la clé par le secret
      - name: Replace API key placeholder
        run: |
          find ./assets -type f -name "index*.js" | while read file; do
            # Remplace la chaîne DEFAULT_API_KEY:"..." par la valeur du secret HF_API_KEY
            sed -i "s/DEFAULT_API_KEY:\"[^\"]*\"/DEFAULT_API_KEY:\"${{ secrets.HF_API_KEY }}\"/g" "$file"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
